### ISSUE TITLE
Wykład 6 - Zadanie 4

### ISSUE THREAD

**Issue by koseq** [daftcode/daftacademy-python4beginners-autumn2018#15]
Czy przypadkiem nie ma błędu w ostatnim teście w tym zadaniu?
`assert median_of_top_five('personal_data_homework.csv', 'LO') == Decimal("5104.84")`
Mi mediana wychodzi 5132.75  i 5 najwyższych zarobków to:
`[Decimal('5187.70'), Decimal('5185.62'), Decimal('5132.75'), Decimal('5104.84'), Decimal('5077.22')]`

**Comment by pawelswiecki** [comment]
Weryfikujemy.

**Comment by pawelswiecki** [comment]
@koseq Przy pewnej interpretacji treści zadania Twoja odpowiedź jest poprawna. Uściśliliśmy opis zadania (zob. fragment `Update`). Teraz treść powinna być jednoznaczna i ma prowadzić do przejścia testów :) Dzięki za zwrócenie uwagi na problem.

Jeśli to rozwiązuje Twój problem, to zamknij proszę ten issue :)

**Comment by migasmonika** [comment]
Czy komuś przeszły testy? Po uruchomieniu kodu dostaję Error: 

> FileNotFoundError: [Errno 2] No such file or directory: 'personal_data_homework.csv

Zastanawiam się czy problem tkwi w moim rozwiązaniu czy może plik csv nie jest widoczny w testach.

**Comment by koseq** [comment]
no nie ma dodanego pliku csv - chyba przez przypadek, ja sobie sama go
utworzylam i skopiowalam dane z tego przy pozostalych zadaniach

czw., 6.12.2018, 17:46 użytkownik migasmonika <notifications@github.com>
napisał:

**Comment by migasmonika** [comment]
No tak -- nie zauważyłam tej opcji :) Dzięki!

**Comment by koseq** [comment]
@migasmonika Nie ma za co :) @pawelswiecki zupełnie nie zauważyłam tej kolumny, sprawa załatwiona, dzięki!
