### ISSUE TITLE
Wykład 6 - Zadanie 1

### ISSUE THREAD

**Issue by magdakusiak** [daftcode/daftacademy-python4beginners-autumn2018#16]
Cześć

W zadaniu 1 jest jakiś kłopot z testami. Jeżeli do otwierania pliku użyjemy metody `open()` i podamy jej więcej niż jeden argument:
```
open(filename, 'r')
```
to test nie przechodzi, ze względu na zbyt dużą liczbę argumentów podaną do `__init__` jakiejś innej klasy:

```
TypeError: __init__() takes 2 positional arguments but 3 were given
```

(mimo, że jako drugi argument pozycyjny funkcji `open()` podano domyślną wartość) 

To samo dzieje się, gdy podamy jakiś inny argument poza jedynym wymaganym (np. zmienimy kodowanie):

```
open(filename, encoding='utf8')
```

Udało mi się uniknąć tego problemu nie podając kodowania, ale nie wiem czy przez to nie tracę poprawnej obsługi "nietypowych" znaków

```
open(filename)
```
Czy jest jakiś inny sposób żeby wczytać ten plik z podaniem własnego, innego niż domyślne, kodowania?

**Comment by pawelswiecki** [comment]
Sprawdzamy co jest nie tak.

**Comment by pawelswiecki** [comment]
Nie mogę odtworzyć tego błędu. Czy mogłabyś wkleić większy fragment kodu, taki, bym po wklejeniu do `repl.it`'a zobaczył ten `TypeError`? Tylko pamiętaj o usunięciu kodu rozwiązania zadania ;)

**Comment by alexandrova-s** [comment]
Hej :)
czy ktoś może wie co to za błąd? Jakbym miała coś źle w pythonie w kompuerze

  File "main.py", line 10, in count_unique_id_numbers_before_clean
    for row in reader:
  File "/usr/local/lib/python3.6/csv.py", line 111, in __next__
    self.fieldnames
  File "/usr/local/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "/usr/local/lib/python3.6/encodings/cp1250.py", line 23, in decode

**Comment by magdakusiak** [comment]
import csv
def count_unique_id_numbers_before_clean(filename):
    filehook = open(filename, 'r')
    object_reader = csv.reader(filehook)

**Comment by pawelswiecki** [comment]
Ogólnie zakładajcie nowy issue na każdy nowy problem.

**Comment by magdakusiak** [comment]
Jeżeli uzupełnimy ten kod o brakujące elementy funkcji, to test i tak nie przejdzie - z komunikatem takim jak na screenie

![image](https://user-images.githubusercontent.com/45140204/49657142-44442380-fa3f-11e8-9857-cfd4208c940b.png)

**Comment by pawelswiecki** [comment]
OK, potwierdzam wystąpienie błędu. Badamy problem. 

Ogólnie testy powinny przechodzić bez sprecyzowanego kodowania, bo default to UTF-8, a właśnie w tym kodowaniu jest plik csv. Potwierdź proszę, czy testy Ci przeszły dla gotowej implementacji rozwiązania.

**Comment by pawelswiecki** [comment]
@magdakusiak 

Update: nasz sztab specjalistów naprawił już problem. Potwierdź proszę czy już działa.

Dzięki za zgłoszenie problemu! :)

**Comment by magdakusiak** [comment]
Działa :)

**Comment by pawelswiecki** [comment]
Super! Zamykam issue. @alexandrova-s jeśli nie rozwiązałaś swojego problemu, to załóż proszę drugi issue poświęcony jemu.

**Comment by pawelswiecki** [comment]
@magdakusiak Super! Mógłbym prosić o zamknięcie issue?

@alexandrova-s jeśli nie rozwiązałaś swojego problemu, to załóż proszę drugi issue poświęcony jemu.
