### ISSUE TITLE
Wyklad 6 - Zadanie 4

### ISSUE THREAD

**Issue by Velociraptorvelraptor** [daftcode/daftacademy-python4beginners-autumn2018#17]
W pliku personal_data
Agata,Malinowska,ZA/999331/2010,2010-12-27,451935.00000000006 pln,ZARZĄD ,1
Agata,Malinowska,ZA/999331/2010,2010-12-27,451935.00000000006 pln,ZARZĄD ,1
wiersz 312 i 630 sa takie same poprzez co najwieksze zarobki w zarzadzie to:

451935
451935
90640
89045
84980

i mediana wynosi 90640, a powinna 89045, do weryfikacji.

**Comment by pawelswiecki** [comment]
Zadaniem tej funkcji nie jest radzenie sobie z duplikatami. Zatem nie usuwamy duplikatów. Jeśli wiersz jest powtórzony, to traktujemy je jako dwa różne wiersze. Zaraz pojawi się to jako `Update 2` w opisie zadania.

Dzięki za zwrócienie uwagi na niedopowiedzenie!

Jeśli to rozwiązjue Twój problem, to zamknij proszę issue :)
