### ISSUE TITLE
Wykład 1 - Zadanie 4

### ISSUE THREAD

**Issue by Piotr296** [daftcode/daftacademy-python4beginners-autumn2018#2]
Czy to zadanie powinno zostać rozwiązane z pomocą powerseta?

def pset(myset):
  if not myset: 
    return [set()]

  r = [ ]
  for y in myset:
    sy = set((y,))
    for x in pset(myset - sy):
      if x not in r:
        r.extend([x, x|sy])
  return r

result = pset(set(U))
print(result)

**Comment by Velociraptorvelraptor** [comment]
You can always look up for sth useful in itertools lib ;--).

**Comment by Piotr296** [comment]
I find there this recipes. But it doesn't work. Should I import sth first?

def powerset(iterable):
    "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(len(s)+1))

Could you please explain me what is frozenset?

**Comment by BielinskiLukasz** [comment]
Frozenset is an immutable set :)
https://docs.python.org/3/library/stdtypes.html?highlight=frozenset#set-types-set-frozenset

**Comment by wuPiotrek** [comment]
Cześć,

Mam następujące problemy z zadaniem 4:
- chrome na PC nie odczytuje poprawnie emotikon > jakiś dodatek który to naprawi? dodam, że na iphone emotikony z zadania wyświetlane są poprawnie.
- repl.it nie chce zatwierdzić testów, wyskakuje następujący błąd: 
![image](https://user-images.githubusercontent.com/44615713/47957302-9367e600-dfb3-11e8-8d85-2793b8aac643.png)

Dodam, że program lokalnie działa bez problemu (dla różnych, 10-elementowych zbiorów)

Na repl.it program przechodzi następujące testy:

![image](https://user-images.githubusercontent.com/44615713/47957358-8eeffd00-dfb4-11e8-91ce-c0097732029f.png)

Proszę o informację, czy nie trafiam w "klucz" i dlatego nie chce mi zaakceptować projektu, czy repl.it nie radzi sobie z powersetem przy 10-elementowym zbiorze.

**Comment by Piotr296** [comment]
Jeśli w pierwszej procedurze zamienię sety na frozensety to otrzymuje frozensety jako zbiory wewnętrzne (o ile dobrze rozumiem polecenie). Natomiast wciąż nie przechodzi mi testów i mam podobny problem co wuPiotrek  - "too long to execute (...)"

def pset(myset):
  if not myset:
    return [frozenset()]

  r = []
  for y in myset:
    sy = frozenset((y,))
    for x in pset(myset - sy):
      if x not in r:
        r.extend([x, x|sy])
  return r

result = pset(U)
print(result)

**Comment by wuPiotrek** [comment]
Sprawdź, czy w ten sposób wynik wyświetla Ci jako set czy jako listę :) 
Kod mam podobny, sy mam zdefiniowane jako (zwykły)set.

**Comment by Piotr296** [comment]
Wyświetla mi jako listę. Hm. A powinno jako seta?

**Comment by wuPiotrek** [comment]
![image](https://user-images.githubusercontent.com/44615713/47957823-7cc68c80-dfbd-11e8-8a0c-db25db9c21e8.png)

![image](https://user-images.githubusercontent.com/44615713/47957834-b8615680-dfbd-11e8-976f-7dc888494a6f.png)

**Comment by BielinskiLukasz** [comment]
@Piotr296 
Trzeba uważać przy inicjalizacji zmiennej, można przypadkiem wpaść w kolekcję, której nie chcieliśmy :)
![image](https://user-images.githubusercontent.com/35973985/47967017-27d85400-e059-11e8-8b37-c616421dcf56.png)

@wuPiotrek 
Dopisz kilka własnych asercji, może uda Ci się znaleźć problem. Ewentualnie wypisz w konsolę wynik metody dla mniejszego zbioru (np {1, 2, 3}) i sprawdź, czy działa poprawnie :)

**Comment by wuPiotrek** [comment]
@BielinskiLukasz 

![image](https://user-images.githubusercontent.com/44615713/47967148-a1247680-e05a-11e8-97ed-31e930c638b2.png)

![image](https://user-images.githubusercontent.com/44615713/47967154-ae416580-e05a-11e8-8cbd-ae720d4e7bec.png)

Z seta 3-elementowego tworzy powerset 8-elementowy (2^3). Wydaje się ok

**Comment by BielinskiLukasz** [comment]
Widać mamy podobny algorytm, bo mam nawet w takiej samej kolejności :) Niestety wydaje się ok w takim razie, przynajmniej jeżeli chodzi o działanie. Może testy sprawdzają też wydajność?

Sprawdź może jeszcze przypadek pustego seta (czy zwróci set zawierające pusty frozenset), jeden ze skrajnych przypadków :) Może błędnie przypuszczam, że dla "jakiegoś" przypadku, który zapewne jest w testach, Twój algorytm wpada w nieskończoną rekurencję, ale warto sprawdzić jeszcze ten przypadek.

**Comment by stankevichk** [comment]
Zawsze można skorzystać z itertools, a dokładniej itertools.combinations(x,y)

**Comment by wuPiotrek** [comment]
Po wykorzystaniu innej (prostszej) pętli do stworzenia powerseta zadanie przeszło testy :)

**Comment by santaxl** [comment]
To zadanie trzeba było zrobić z funkcją powerset? 
A ja się z rozwiązaniem na bitach męczyłem XD
Chociaż wyszło elegancko i przeszło wszystkie testy

**Comment by Piotr296** [comment]
Jak już jest po czasie to ktoś się chcę podzielić rozwiązaniem ;-)?

Ja na razie zacząłem próbować z:
import itertools

for i in range(0,len(U)):
    result = set(itertools.combinations(U,i))

print(result)

Ale pętla mi nie działa

**Comment by santaxl** [comment]
@Piotr296 Jasne, trzymaj. Chociaż w założeniu autorów to trzeba było inaczej zrobić, dam głowę XD

U = {'👻', '🕵', '🔺', '🐉', '🐍', '🦂', '🔥', '🌻', '🐙', '🌌'}

result = set()

numOfSubsets = 2**len(U)
for i in range(numOfSubsets):
  tempSet = set()
  // convert to binary
  num = "{0:b}".format(i)
  
 // add 0s as most significant bits, so all "i"s are made of 10 bits (10, because we have a set of 10 elements)
  while len(num) < len(U):
    num = '0' + num
    
  // the idea is simple - '0' means exclude, '1' means include
  for j in range(len(num)):    
    if num[j] == '1':
      tempSet.add(list(U)[j])
      result.add(frozenset(tempSet))

result.add(frozenset())

**Comment by Lozdowski** [comment]
W dniu pon., 5.11.2018 o 00:12 Dominik Mańkowski <notifications@github.com>
napisał(a):

**Comment by Piotr296** [comment]
santaxl ja wkleiłem Twój kod i nie przechodzi u mnie testów. Co dziwniejsze daje wynik taki sam jak mój pierwotny kod..

**Comment by ArekP2** [comment]
Też podejrzewam, że chodziło o coś innego, ale nie chciało mi się wymyślać koła na nowo. Skoro są gotowe biblioteki i przechodzi testy :)

# zadanie 4
from itertools import chain, combinations

U = {'👻', '🕵', '🔺', '🐉', '🐍', '🦂', '🔥', '🌻', '🐙', '🌌'}

result = set()

for r in range(len(U)+1):  # for every r length subsequence
  for t in combinations(U, r):  # for every t tuple of subsequence of elements
    result.add(frozenset({e for e in chain(t)}))  # chain returns elements from tuple

assert frozenset(('👻', '🕵', '🔺', '🐉', '🐍', '🦂', '🔥', '🌻', '🐙', '🌌')) in result

**Comment by mrmumu24** [comment]
result = {frozenset()}
for x in U:
    tmp = set()
    for y in result:
        tmp.add(y.union(x))
    result.update(tmp)

**Comment by mrtovsky** [comment]
Troche juz pozno, ale nawet dla czystej ciekawosci, jak mozna poslugiwac sie generatorami, polecam zapoznac sie z zalaczonym [rozwiazaniem](https://stackoverflow.com/a/36796196) ze stacka:
