### ISSUE TITLE
Wyklad 2 zadanie 3

### ISSUE THREAD

**Issue by Angerton** [daftcode/daftacademy-python4beginners-autumn2018#3]
Czy aby na pewno dobrze napisaliscie testy w wykladzie 2 zadaniu 3?

Kod przechodzi assert ktory jest w terminalu:
assert char_frequency("576") == {'5': 1, '6': 1, '7': 1}

A potem i tak wyrzuca mi blad:
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 27, in test_correctness
    assert result1 == {5: 1, 6: 1, 7: 1}
AssertionError

Wydaje mi sie ze nie daliscie ptaszków ('') przy nazwie kluczy w: assert result1 == {5: 1, 6: 1, 7: 1}.

Pozdrawiam

**Comment by Piotr296** [comment]
Mi kod przeszedł

**Comment by ArekP2** [comment]
Mi też :)

**Comment by Angerton** [comment]
Co robie zle?:

def char_frequency(x=''):
  if type(x)==str:
    mydict = {}
    for letter in x:
      mydict[letter] = x.count(letter)
    return mydict  
  else:
    return {}

**Comment by ArekP2** [comment]
@Angerton 
1. Zauważ, że jak dodasz konwersje argumentu do string, to Twój kod przejdzie testy:
```
def char_frequency(x=''):
    if type(str(x))==str:
```
2. Podejrzewam, że jakiś przypadek testowy zawiera bytes object, który bez tej dodatkowej konwersji nie spełnia Twojego if-a.
> Note that in Python 3, unicode and basestring no longer exist (there is only str) and a bytes object is no longer a kind of string (it is a sequence of integers instead).
[https://www.python.org/dev/peps/pep-0008/](url)

3. Ja w swoim kodzie sprawdzam tylko, czy argument nie jest None (bo z treści zadania rozumiem, że argument jest stringiem) i  wtedy zwracam pusty słownik. I taki kod przechodzi testy :)

**Comment by pszeny** [comment]
miałem ten sam problem i jak wywaliłem warunek na to żeby argument był stringiem to działa
