### ISSUE TITLE
Wykład 3 - Classes

### ISSUE THREAD

**Issue by Piotr296** [daftcode/daftacademy-python4beginners-autumn2018#6]
Może komuś przyda się dodatkowe wyjaśnienie: https://www.youtube.com/watch?v=ZDa-Z5JzLYM&list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc&fbclid=IwAR2JZF3K4_XG58xkEi3nTzy3nZ51lQsN59T76N2u3AdVuYYW87byhJ-5GAg

Jeśli ktoś (jak ja) preferuje wizualne wyjaśnienie wszystkich niejasności, albo powtórzenie materiału z wykładu to polecam ten Tutorial. Oczywiście w języku angielskim ;-)

**Comment by wjurga** [comment]
@Piotr296 dzięki za link :) również polecam filmy Corey'a.
