### ISSUE TITLE
Wykład 3  - Zadanie 1

### ISSUE THREAD

**Issue by Velociraptorvelraptor** [daftcode/daftacademy-python4beginners-autumn2018#7]
Hej, 
skrypt przechodzi mi wszystkie testy oprócz poniższego: 
_**Failed tests
increase_value**_
Jak mniemam funkcja __iadd__ poprawnie skonfigurowana powinna pozwolić przejść ten test.
Jakieś wskazówki? Dodam, że test "increase_value_by_int" przechodzi poprawnie.

**Comment by FHoffmannCode** [comment]
Cześć,
Upewnij się, że po zwiększeniu wartości na pewno skracasz ułamek. Z tego co widziałem to dość popularny błąd.

**Comment by Velociraptorvelraptor** [comment]
Zgadza się, dziękuję.

**Comment by Piotr296** [comment]
Zostały mi 3 testy do przejścia. Jakaś podpowiedź jak je zaimplementować, co poprawić?
- increased_value 
def __iadd__(self, other):
	self.numerator += other.numerator
	return self 

- increase_value_by_int
Do tej metody w ogóle nie wiem jak się zabrać. Gdzie ją zaimplementować? Razem z __iadd__?

- add_fraction_to_int
Próbowałem to rozwiązać w ten sposób:
	def toFraction(self, o):
		if type(o) == int:
			return MyFraction(o)
		return o
I potem: 
	def __add__(self, other):
		other = self.toFraction(other)
		commonDenominator = self.lcm(self.denominator, other.denominator)
                (...)
Ale nie działa :(

**Comment by BielinskiLukasz** [comment]
> increased_value
> def iadd(self, other):
> self.numerator += other.numerator
> return self

Przy dodawaniu ułamków musisz uwzględnić różne mianowniki. W iadd tego nie widzę, może nie wkleiłeś całego kodu? :)

> increase_value_by_int
> Do tej metody w ogóle nie wiem jak się zabrać. Gdzie ją zaimplementować? Razem z iadd?

Jest to połączenie problemu dodawania int i inkrementacji. Jak uda Ci się rozwiązać pozostałe, to raczej ten problem powinien też zniknąć :)

> add_fraction_to_int
> Próbowałem to rozwiązać w ten sposób:
> def toFraction(self, o):
> if type(o) == int:
> return MyFraction(o)
> return o
> I potem:
> def add(self, other):
> other = self.toFraction(other)
> commonDenominator = self.lcm(self.denominator, other.denominator)
> (...)
> Ale nie działa :(

Zauważ, że w tym przypadku musisz obdłużyć dodanie ułamka do int, np.
> x = MyFraction(1, 2) + 1

**Comment by Piotr296** [comment]
Ad. 1
def __iadd__(self, other):
		return self + other
W tym wypadku "+" powinien mi się odwoływać do metody __add__ tak? O ile zrozumiałem cokolwiek z metod magicznych?

Ad. 3
Tyle, że dodawanie (MyFraction(1, 4) + 1) mi działa. Nie działa mi  (1 + MyFraction(1, 4))

Próbowałem to rozwiązać poprzez zamianę int na MyFraction:
	def __add__(self, other):
	  if self == int:
	    self = self.toFraction(self)
Ale chyba coś tu przekombinowałem?

**Comment by BielinskiLukasz** [comment]
> Ad. 1
> def iadd(self, other):
> return self + other
> W tym wypadku "+" powinien mi się odwoływać do metody add tak? O ile zrozumiałem cokolwiek z metod magicznych?

Nie jestem do końca pewien w czym leży problem tutaj. Wcześniej zobaczyłem jedynie zsumowanie wykładników ułamka, skąd wniosek, że może być coś źle z samą implementacją dodawania :P Ale skoro dodawanie int działa to raczej nie w tym problem.

> Ad. 3
> Tyle, że dodawanie (MyFraction(1, 4) + 1) mi działa. Nie działa mi (1 + MyFraction(1, 4))
> 
> Próbowałem to rozwiązać poprzez zamianę int na MyFraction:
> def add(self, other):
> if self == int:
> self = self.toFraction(self)
> Ale chyba coś tu przekombinowałem?

Tutaj opis pozwala mi przypuszczać co nie gra :) Metoda add zdefiniowana jest dla MyFraction i wywołuje się tylko gdy pierwszym argumentem dodawania jest właśnie MyFraction (dlatego działa pierwszy przypadek), a nie gdy jest to int (drugi przypadek). Podrzucam hasło Reflected arithmetic operators, powinno pomóc w rozwiązaniu problemu :)

**Comment by Piotr296** [comment]
Ad. 3. Zadziałało! Dzięki! Jeśli ktoś ma podobny problem jak ja, to tu macie opis Reflected Arithmetic Operators: https://rszalski.github.io/magicmethods/ i ich zastosowanie rozwiązuje problem.

**Comment by bulkazszynka** [comment]
Cześć,
jaki może być powód nie spełniania testów: increase_value oraz increase_value_by_int? Wszystkie inne testy przechodzą, a tak jak sprawdzam printem to działania:
a = MyFraction(4,4)
a += MyFraction(2,3)
a += 2
produkują poprawne wyniki.

**Comment by Piotr296** [comment]
Masz ten sam błąd co ja. Też ciągle szukam rozwiązania. Z assertów wynika, że to ma być jeden obiekt.

**Comment by bulkazszynka** [comment]
Twoja podpowiedź okazała się być trafna. W ramach podpowiedzi powiem, że iadd musi zwrócić obiekt, którego id będzie takie samo jak wchodzącego do niego selfa, a Twój kod zwraca nowy obiekt.

**Comment by Piotr296** [comment]
Dzięki. Działa! Parafrazując elektrodę: temat do zamknięcia :D
